
local camera = require "orthographic.camera"
go.property("mouse_pos", vmath.vector3())

function init(self)
	self.speed = 1000
	self.pos = go.get_position()
	self.timer = 5
	self.mouse_pos = camera.screen_to_world(nil, self.mouse_pos)
	self.direction = vmath.normalize(vmath.vector3(self.mouse_pos.x - self.pos.x, self.mouse_pos.y - self.pos.y, 0))
	
	local angle = math.atan2( self.mouse_pos.y- self.pos.y , self.mouse_pos.x - self.pos.x) - math.pi/2
	go.set_rotation(vmath.quat_rotation_z(angle))
	
end

function update(self, dt)
	self.timer = self.timer - dt
	if self.timer <= 0 then
		go.delete()
	end
	self.pos = self.pos + self.direction * self.speed * dt
	go.set_position(self.pos)
end

function on_message(self, message_id, message, sender)

end

